modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "GNU LGPLv3"

[[mods]]
modId = "nf_test_mod"
version = "${version}"
displayName = "mc-vr-api"
authors = "hammy3502"
description = '''
VR API mod that allows mods to integrate into Vivecraft.
'''
displayTest = "NONE"
#logoFile = ""

[[dependencies.nf_test_mod]]
modId = "neoforge"
type = "required"
versionRange = "[20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nf_test_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.nf_test_mod]]
modId = "architectury"
type = "required"
versionRange = "[11.0.11,)"
ordering = "AFTER"
side = "BOTH"